# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rwatling/Projects/gpu_sudoku

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rwatling/Projects/gpu_sudoku

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rwatling/Projects/gpu_sudoku/CMakeFiles /home/rwatling/Projects/gpu_sudoku//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rwatling/Projects/gpu_sudoku/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _cuda

# Build rule for target.
_cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _cuda
.PHONY : _cuda

# fast build rule for target.
_cuda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cuda.dir/build.make CMakeFiles/_cuda.dir/build
.PHONY : _cuda/fast

#=============================================================================
# Target rules for targets named _cpp

# Build rule for target.
_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _cpp
.PHONY : _cpp

# fast build rule for target.
_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/build
.PHONY : _cpp/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/argument_parsing.o: src/argument_parsing.cpp.o
.PHONY : src/argument_parsing.o

# target to build an object file
src/argument_parsing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/argument_parsing.cpp.o
.PHONY : src/argument_parsing.cpp.o

src/argument_parsing.i: src/argument_parsing.cpp.i
.PHONY : src/argument_parsing.i

# target to preprocess a source file
src/argument_parsing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/argument_parsing.cpp.i
.PHONY : src/argument_parsing.cpp.i

src/argument_parsing.s: src/argument_parsing.cpp.s
.PHONY : src/argument_parsing.s

# target to generate assembly for a file
src/argument_parsing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/argument_parsing.cpp.s
.PHONY : src/argument_parsing.cpp.s

src/main.o: src/main.cu.o
.PHONY : src/main.o

# target to build an object file
src/main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cu.o
.PHONY : src/main.cu.o

src/main.i: src/main.cu.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cu.i
.PHONY : src/main.cu.i

src/main.s: src/main.cu.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cu.s
.PHONY : src/main.cu.s

src/sudoku.o: src/sudoku.cu.o
.PHONY : src/sudoku.o

# target to build an object file
src/sudoku.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cuda.dir/build.make CMakeFiles/_cuda.dir/src/sudoku.cu.o
.PHONY : src/sudoku.cu.o

src/sudoku.i: src/sudoku.cu.i
.PHONY : src/sudoku.i

# target to preprocess a source file
src/sudoku.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cuda.dir/build.make CMakeFiles/_cuda.dir/src/sudoku.cu.i
.PHONY : src/sudoku.cu.i

src/sudoku.s: src/sudoku.cu.s
.PHONY : src/sudoku.s

# target to generate assembly for a file
src/sudoku.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cuda.dir/build.make CMakeFiles/_cuda.dir/src/sudoku.cu.s
.PHONY : src/sudoku.cu.s

src/timer.o: src/timer.cpp.o
.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/utilities.o: src/utilities.cpp.o
.PHONY : src/utilities.o

# target to build an object file
src/utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/utilities.cpp.o
.PHONY : src/utilities.cpp.o

src/utilities.i: src/utilities.cpp.i
.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/utilities.cpp.i
.PHONY : src/utilities.cpp.i

src/utilities.s: src/utilities.cpp.s
.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_cpp.dir/build.make CMakeFiles/_cpp.dir/src/utilities.cpp.s
.PHONY : src/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... _cpp"
	@echo "... _cuda"
	@echo "... main"
	@echo "... src/argument_parsing.o"
	@echo "... src/argument_parsing.i"
	@echo "... src/argument_parsing.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sudoku.o"
	@echo "... src/sudoku.i"
	@echo "... src/sudoku.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

